name: "Antora Site with Lunr Search"
description: "Generates an Antora site with Lunr Search integrated"
branding:
  icon: book-open
  color: yellow
inputs:
  antora_playbook:
    description: 'The Antora playbook file'
    required: true
    default: 'site.yaml'
  site_sources_path:
    description: 'The path relative to workspace root, where the asciidoc sources exits'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.antora_playbook}}
     - ${{ inputs.site_sources_path }}